name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
  merge_group:
    paths-ignore:
      - "**.md"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          [
            "",
            "--no-default-features",
            "--all-targets --all-features",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: RUSTFLAGS="--deny warnings" cargo clippy ${{ matrix.features }}

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RUSTDOCFLAGS="-Dwarnings" cargo doc --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  check-format:
    name: check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --check

  # Used to signal to branch protections that all other jobs have succeeded.
  all-jobs-succeed:
    name: All checks succeeded
    if: success()
    runs-on: ubuntu-latest
    needs: [check, test, check-format, doc]
    steps:
      - name: Mark the job as successful
        run: exit 0
        
  